### ISSUE TITLE
Social icons

### ISSUE THREAD

**Issue by kirota2908** [Ph0bos87/rebuyDemo#16]
Zalijepiti da putuju po stranici

https://www.facebook.com/RebuyStarsZagreb/
https://www.instagram.com/zagrebrebuystars/

https://www.facebook.com/Rebuy-Stars-Vara%C5%BEdin-704857049952107/
https://www.instagram.com/rebuy.stars.vz/?hl=hr

**Comment by Ph0bos87** [comment]
rijeseno
