### ISSUE TITLE
Landing page - logo kod mene na krivom mjestu

### ISSUE THREAD

**Issue by kirota2908** [Ph0bos87/rebuyDemo#8]
![image](https://user-images.githubusercontent.com/78867380/108980573-18e39880-768c-11eb-974e-9e0b9d0e1a8d.png)
KAd smanjim ekran je ok.. na velikom ni dobro..

**Comment by kirota2908** [comment]
Logo je sad ok, ali klubovi nisu.. dobro je dok ne odradi animaciju do kraja, i onda dobijemo ovako..

![image](https://user-images.githubusercontent.com/78867380/109115430-5e14d280-773f-11eb-8ef6-da3b85fd755c.png)

A ovo je u procesu dok još animira..
![image](https://user-images.githubusercontent.com/78867380/109115515-7c7ace00-773f-11eb-8061-3265a0759cf1.png)

**Comment by Ph0bos87** [comment]
Ovo je isto rijeseno...
